name: XTC LLVM Tools Wheels Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
          pip list
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: PIP Cache
        uses: actions/cache@v4
        with:
          path: ~/pip_cache
          key: ${{ runner.os }}-pip-cache
      - name: CCache Cache
        uses: actions/cache@v4
        with:
          path: ~/ccache
          key: ${{ runner.os }}-ccache
      - name: Checkout LLVM
        run: |
          ./checkout-llvm.sh
      - name: Install macOS Brew Packages
        if: runner.os == 'macOs'
        run: |
          brew install ccache
      - name: Build Wheels
        run: |
          export BUILD_PIP_CACHE_DIR=$HOME/pip_cache
          export BUILD_CCACHE_DIR=$HOME/ccache
          ./build-wheels.sh
      - name: Store distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-xtc-llvm-tools-${{ runner.os }}
          path: wheelhouse/
